# 프로젝트별로 로거 환경 설정 파일은 변경해야 한다.
version: 1
objects:
  queue:
    class: queue.Queue
    maxsize: 1000
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: 'ieddit.log' # 프로젝트 시작시 수정필요
    formatter: simple
  queue_listener:
    # 프로젝트 시작시 수정필요
    class: log_utils.logger_util.QueueListenerHandler
    handlers:
      - cfg://handlers.console
      - cfg://handlers.file
    queue: cfg://objects.queue
loggers:
  __bt_logger__:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: false        
root:
  level: DEBUG
  handlers:
    - console
    - file

